CURPWD = $(shell pwd)

THIRD_PARTY_HOME=/usr/local/third_party
NGX_ROOT=$(CURPWD)/../ngx

CC =	gcc
CFLAGS =   -W -Wall -Wpointer-arith -Wno-unused-parameter  -g3  -I .  -DNDK_SET_VAR -Wno-unused-function -Wno-missing-field-initializers -D_POSIX_C_SOURCE=200112L --std=c99 -Isrc -DNDK_SET_VAR
CXXFLAGS +=  -g3 -MMD -Wall -Werror -fPIC
CPP =	g++ 
LINK =  g++ -rdynamic

INCLUDES +=     -I objs \
	-I $(THIRD_PARTY_HOME)/yajl/include \
	-I $(THIRD_PARTY_HOME)/pcre/include \
	-I exts/nginx_tcp_proxy_module/modules \
	-I exts/nginx_tcp_proxy_module/parsers \
	-I exts/nginx_tcp_proxy_module


STATICLIBS += \
	$(THIRD_PARTY_HOME)/pcre/lib/libpcre.a	\
	$(THIRD_PARTY_HOME)/expat-2.1.0/lib/libexpat.a

c:	objs/client.o	\
	objs/socket.o
	
	$(LINK) -o objs/c \
	objs/client.o	\
	objs/socket.o	\
	-Wl,-E  $(STATICLIBS)

s: objs/server.o	\
	objs/socket.o
	
	$(LINK) -o objs/s \
	objs/server.o   \
	objs/socket.o	\
	-Wl,-E $(STATICLIBS)

objs/client.o:	$(CORE_DEPS) \
	client.c
	$(CC) -c $(CFLAGS) $(CORE_INCS) \
		-o objs/client.o \
		client.c

objs/server.o:	$(CORE_DEPS) \
	server.c
	$(CC) -c $(CFLAGS) $(CORE_INCS) \
		-o objs/server.o \
		server.c


objs/socket.o:	$(CORE_DEPS) \
	socket.c
	$(CC) -c $(CFLAGS) $(CORE_INCS) \
		-o objs/socket.o \
		socket.c


clean:
	rm -rf objs/*

rc:
	./objs/c

rs:
	nohup ./objs/s 9999 &
	tail -f nohup.out

